---
- name: Ensure build dependencies
  ansible.builtin.apt:
    pkg:
      - gnupg
      - software-properties-common
      - wget
  tags:
    - zandronum

- name: Add the Apt signing key
  ansible.builtin.apt_key:
    url: http://debian.drdteam.org/drdteam.gpg
    state: present
  tags:
    - zandronum

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://debian.drdteam.org/ stable multiverse
    state: present
  tags:
    - zandronum

- name: Add the Zandronum package
  ansible.builtin.apt:
    pkg:
      - zandronum-server
  tags:
    - zandronum

- name: Update the linker to look for the included libraries
  ansible.builtin.shell: |
    echo '/usr/games/zandronum' > /etc/ld.so.conf.d/zandronum.conf
    ldconfig
  tags:
    - zandronum

- name: Create zandronum user
  ansible.builtin.user:
    name: zandronum
    shell: /bin/bash
  tags:
    - zandronum

- name: Ensure config directory exists
  ansible.builtin.file:
    path: /home/zandronum/.config/zandronum
    state: directory
  tags:
    - zandronum

- name: Copy default configuration
  ansible.builtin.copy:
    src: ./
    dest: /home/zandronum/.config/zandronum/
    owner: zandronum
    group: zandronum
    mode: 0644
  tags:
    - zandronum

- name: Add server scripts
  ansible.builtin.import_tasks: scripts.yml
  tags:
    - zandronum
