---
- name: ensure build dependencies
  apt:
    pkg:
      - gnupg
      - software-properties-common
      - wget

- name: Add the Apt signing key
  apt_key:
    url: http://debian.drdteam.org/drdteam.gpg
    state: present

- name: Add specified repository into sources list
  apt_repository:
    repo: deb http://debian.drdteam.org/ stable multiverse
    state: present

- name: add the Zandronum package
  apt:
    pkg:
      - zandronum-server

- name: update the linker to look for the included libraries
  shell: |
    echo '/usr/games/zandronum' > /etc/ld.so.conf.d/zandronum.conf
    ldconfig

- name: create zandronum user
  user:
    name:  zandronum
    shell: /bin/bash

- name: ensure config directory exists
  file: path=/home/zandronum/.config/zandronum state=directory

- name: copy default configuration
  copy:
    src:   ./
    dest:  /home/zandronum/.config/zandronum/
    owner: zandronum
    group: zandronum
    mode:  0644

- name: add server scripts
  import_tasks: scripts.yml
