---
- name: Ensure wads directory exists
  ansible.builtin.file:
    path: /wads
    state: directory

- name: Handle installation for Debian
  ansible.builtin.import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
  tags:
    - zandronum
