---
- name: Check if the wads directory exists
  ansible.builtin.stat:
    path: /wads
  register: check_wads_dir
  tags:
    - zandronum

- name: Create wads directory if it does not exist
  ansible.builtin.file:
    path: /wads
    owner: root
    group: root
    mode: 0775
    state: directory
  when: not check_wads_dir.stat.exists

- name: Handle installation for Debian
  ansible.builtin.import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
  tags:
    - zandronum
