---
- name: Create user accounts
  ansible.builtin.user:
    name: "{{ item.username }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    home: "{{ item.home }}"
    shell: "{{ item.shell }}"
    uid: "{{ item.uid }}"
  loop: "{{ accounts_users }}"
  tags:
    - accounts

- name: Create SSH directories
  ansible.builtin.file:
    path: "{{ item.home }}/.ssh"
    state: directory
    mode: 0700
    group: "{{ item.group }}"
    owner: "{{ item.username }}"
  loop: "{{ accounts_users }}"
  tags:
    - accounts

- name: Load private keys
  ansible.builtin.copy:
    dest: "{{ item.home }}/.ssh/id_rsa"
    content: "{{ item.private_ssh_key }}"
    mode: 0600
    group: "{{ item.group }}"
    owner: "{{ item.username }}"
  loop: "{{ accounts_users }}"
  tags:
    - accounts

- name: Load public keys
  ansible.builtin.copy:
    dest: "{{ item.home }}/.ssh/id_rsa.pub"
    content: "{{ item.public_ssh_key }}"
    mode: 0644
    group: "{{ item.group }}"
    owner: "{{ item.username }}"
  loop: "{{ accounts_users }}"
  tags:
    - accounts
