---
- name: Ensure build dependencies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - software-properties-common
      - wget

- name: Add the Apt signing key
  ansible.builtin.apt_key:
    url: https://repo.jellyfin.org/jellyfin_team.gpg.key
    state: present

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb https://repo.jellyfin.org/ubuntu {{ ansible_distribution_release }} main"
    state: present

- name: Add the Jellyfin package
  ansible.builtin.apt:
    pkg:
      - jellyfin

- name: Start Jellyfin
  ansible.builtin.service:
    name: jellyfin.service
    state: started
    enabled: yes
