roles:
  - name: acme_sh
    src: https://github.com/frozenfoxx/acme_sh
    version: main
  - name: rywillia.ssh-copy-id
  - name: ansible-role-portainer
    src: https://github.com/shelleg/ansible-role-portainer
    version: master
  - name: laurivan.mealie
  - name: monolithprojects.github_actions_runner
  - name: nickjj.docker
  - name: r_pufky.pihole
  - name: stefangweichinger.ansible_rclone

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general