roles:
  - name: acme_sh
    src: https://github.com/frozenfoxx/acme_sh
    version: main
  - name: ansible-role-portainer
    src: https://github.com/shelleg/ansible-role-portainer
    version: master
  - name: ansible-role-mealie
    src: https://github.com/frozenfoxx/ansible-role-mealie
    version: main
  - name: nickjj.docker
  - name: r_pufky.pihole
  - name: stefangweichinger.ansible_rclone

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general