# Ansible Galaxy
- src: monolithprojects.github_actions_runner
- src: r_pufky.pihole
- src: stefangweichinger.ansible_rclone

collections:
- name: community.docker

# GitHub
- src: https://github.com/frozenfoxx/acme_sh
  version: main
