roles:
  - name: monolithprojects.github_actions_runner
  - name: oefenweb.nfs_client
  - name: r_pufky.pihole
  - name: stefangweichinger.ansible_rclone
  - name: acme_sh
    src: https://github.com/frozenfoxx/acme_sh
    version: main

collections:
- name: community.docker
