---
collections:
  - name: amazon.aws
  - name: ansible.posix
  - name: community.crypto
  - name: community.docker
  - name: community.general

roles:
  - name: andrewrothstein.k9s
  - name: frozenfoxx.accounts
    src: https://github.com/frozenfoxx/ansible-role-accounts
    version: main
  - name: frozenfoxx.ctop
    src: https://github.com/frozenfoxx/ansible-role-ctop
    version: main
  - name: frozenfoxx.mounts
    src: https://github.com/frozenfoxx/ansible-role-mounts
    version: main
  - name: frozenfoxx.task
    src: https://github.com/frozenfoxx/ansible-role-task
    version: main
  - name: geerlingguy.docker
  - name: geerlingguy.nodejs
  - name: lablabs.rke2
  - name: r_pufky.pihole
  - name: stefangweichinger.ansible_rclone
