---
version: "3"

dotenv: [".env"]

env:
  ANSIBLE_CONFIG: "{{.USER_WORKING_DIR}}/ansible.cfg"

vars:
  INVENTORY_PATH: '{{default "inventory" .INVENTORY_PATH}}'

includes:
  ansible:
    taskfile: .taskfiles/ansible.tasks.yml
    optional: true
    env:
      ANSIBLE_HOST_KEY_CHECKING: False

  git:
    taskfile: .taskfiles/git.tasks.yml
    optional: true
    internal: true

  rclone:
    taskfile: .taskfiles/rclone.tasks.yml
    optional: true
    internal: true

tasks:
  default:
    cmds:
      - task -l
    silent: true

  setup:
    desc: "Configure repository for use"
    cmds:
      - task: rclone:install
      - task: git:reset:dir
        vars:
          CLI_ARGS: "{{.USER_WORKING_DIR}}/inventory"
      - task: rclone:copy
        vars:
          RCLONE_SOURCE: "inventory:{{.INVENTORY_PATH}}/"
          RCLONE_DEST: "{{.USER_WORKING_DIR}}/inventory/"
      - task: ansible:galaxy

  update:
    desc: "Update repo"
    cmds:
      - rm -rf .taskfiles
      - git clone https://github.com/frozenfoxx/taskfiles.git .taskfiles
      - git restore .
      - git pull --rebase
