---
version: "3"

dotenv: [".env"]

vars:
  ANSIBLE_ARGS: ""
  ANSIBLE_CONFIG: "{{.USER_WORKING_DIR}}/ansible.cfg"
  RCLONE_ARGS: ""

includes:
  ansible:
    taskfile: .taskfiles/ansible.tasks.yml
    internal: true

  git:
    taskfile: .taskfiles/git.tasks.yml
    internal: true

tasks:
  default:
    cmds:
      - task -l
    silent: true

  hosts:
    desc: "List all inventory hosts"
    cmds:
      - task: ansible:inventory

  lint:
    desc: "Check syntax"
    cmds:
      - task: ansible:lint
