---
version: "3"

dotenv: [".env"]

vars:
  ANSIBLE_ARGS: ""
  ANSIBLE_CONFIG: "{{.USER_WORKING_DIR}}/ansible.cfg"
  RCLONE_ARGS: ""

includes:
  ansible: .taskfiles/ansible.tasks.yml
  internal: true

  git: .taskfiles/git.tasks.yml
  internal: true

tasks:
  hosts:
    desc: "List all inventory hosts"
    cmds:
      - task: ansible:inventory

  lint:
    desc: "Check syntax"
    cmds:
      - task: ansible:lint
