---
version: "3"

dotenv: [".env"]

env:
  ANSIBLE_CONFIG: "{{.USER_WORKING_DIR}}/ansible.cfg"

vars:
  ANSIBLE_ARGS: "-u {{.ANSIBLE_USER}}"
  INVENTORY_PATH: '{{default "inventory" .INVENTORY_PATH}}'

includes:
  ansible:
    taskfile: .taskfiles/ansible.tasks.yml

  git:
    taskfile: .taskfiles/git.tasks.yml
    internal: true

  rclone:
    taskfile: .taskfiles/rclone.tasks.yml
    internal: true

tasks:
  default:
    cmds:
      - task -l
    silent: true

  setup:
    desc: "Configure repository for use"
    cmds:
      - task: rclone:install
      - task: git:pull
      - task: git:reset:dir
        vars:
          CLI_ARGS: "{{.USER_WORKING_DIR}}/inventory"
      - task: rclone:copy
        vars:
          RCLONE_SOURCE: "inventory:{{.INVENTORY_PATH}}/"
          RCLONE_DEST: "{{.USER_WORKING_DIR}}/inventory/"
      - task: ansible:galaxy

  update:
    desc: "Update taskfiles"
    cmds:
      - task: git:submodule:update
