---
- name: Add 32bit architecture installation for Debian
  ansible.builtin.import_tasks: debian-32bit.yml

- name: Add packages for Debian
  ansible.builtin.import_tasks: debian-packages.yml

- name: Install GameDig
  ansible.builtin.import_tasks: debian-gamedig.yml

- name: Create pmcserver user
  ansible.builtin.user:
    name:  pmcserver
    shell: /bin/bash
    append: yes
    groups:
      - staff

- name: Create Ansible temp directory
  ansible.builtin.shell:
    cmd: mkdir -p /home/pmcserver/.ansible/tmp
  become: True
  become_user: pmcserver

- name: Retrieve LinuxGSM script
  ansible.builtin.get_url:
    url: https://linuxgsm.sh
    dest: /home/pmcserver/linuxgsm.sh
    mode: 0755
  become: True
  become_user: pmcserver

- name: Install PaperMC module
  ansible.builtin.shell:
    cmd: ./linuxgsm.sh pmcserver
    chdir: /home/pmcserver
  become: True
  become_user: pmcserver

- name: Install PaperMC
  ansible.builtin.shell:
    cmd: ./pmcserver auto-install
    chdir: /home/pmcserver
  become: True
  become_user: pmcserver

- name: Ensure local share directory exists
  ansible.builtin.file:
    path: "/home/pmcserver/.local/share"
    state: directory
    mode: 0755
    group: pmcserver
    owner: pmcserver

- name: Register if a world mount exists
  ansible.builtin.stat:
    path: /data
  register: world_mount

- name: Link world mount
  ansible.builtin.file:
    src: /data
    path: "/home/pmcserver/.local/share"
    state: link
  when: world_mount.stat.exists

- name: Install server scripts
  ansible.builtin.import_tasks: scripts.yml
