- name: Add paper-world-defaults.yml
  ansible.builtin.template:
    src: paper-world-defaults.yml.j2
    dest: /home/pmcserver/serverfiles/config/paper-world-defaults.yml
    owner: pmcserver
    group: pmcserver
    mode: 0664
