---
plugin: community.general.proxmox
url: "{{ lookup('ansible.builtin.env', 'pm_url') | default('https://proxmox:8006') }}"
user: "{{ lookup('ansible.builtin.env','pm_user') | default('ansible@pve') }}"
password: "{{ lookup('ansible.builtin.env', 'pm_pass') | default('big-secret-pass') }}"
validate_certs: false
want_facts: true
want_proxmox_nodes_ansible_host: false
compose:
  ansible_host: proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ansible.utils.ipaddr('address')
keyed_groups:
  # proxmox_tags_parsed is an example of a fact only returned when 'want_facts=true'
  - key: proxmox_tags_parsed
    separator: ""
    prefix: ""
# groups:
#   rke2_schedulers: "'rke2_scheduler' in (proxmox_tags_parsed|list)"
#   rke2_workers: "'rke2_worker' in (proxmox_tags_parsed|list)"
