---
all:
  hosts:
    homeassistant:
    host-1:
    host-2:
    htpc-1:
    printer-2:

desktops_windows:
  hosts:
    htpc-1:

homeassistant:
  hosts:
    homeassistant:

hypervisors:
  hosts:
    host-1:
    host-2:

octopi:
  hosts:
    printer-2:
