---
zandronum_rcon_pass: "{{ lookup('amazon.aws.aws_secret', 'ansible-bricksandblocks/inventory/group_vars/all.ZANDRONUM_RCON_PASS', nested=true) }}"
zandronum_server_pass: "{{ lookup('amazon.aws.aws_secret', 'ansible-bricksandblocks/inventory/group_vars/all.ZANDRONUM_SERVER_PASS', nested=true) }}"
