---
- name: Remove existing NodeJS
  ansible.builtin.apt:
    pkg:
      - nodejs
      - npm
    autoremove: yes
    state: absent
    purge: yes
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags:
    - nodejs

- name: Fetch Node.js installer
  ansible.builtin.uri:
    url: https://deb.nodesource.com/setup_16.x
    return_content: yes
  register: nodejs_installer
  tags:
    - nodejs

- name: Run Node.js installer
  ansible.builtin.shell:
    cmd: bash -
    stdin: "{{ nodejs_installer.content }}"
  tags:
    - nodejs

- name: Install Node.js
  ansible.builtin.apt:
    pkg:
      - nodejs
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags:
    - nodejs
