---
- name: remove existing NodeJS
  apt:
    pkg:
      - nodejs
      - npm
    autoremove: yes
    state: absent
    purge: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: fetch Node.js installer
  uri:
    url: https://deb.nodesource.com/setup_16.x
    return_content: yes
  register: nodejs_installer

- name: run Node.js installer
  shell:
    cmd: bash -
    stdin: "{{ nodejs_installer.content }}"

- name: install Node.js
  apt:
    pkg:
      - nodejs
  environment:
    DEBIAN_FRONTEND: noninteractive