---
- name: Create tautulli system group
  group:
    name: tautulli
    system: yes
  tags:
    - tautulli

- name: Create tautulli user
  user:
    name: tautulli
    group: tautulli
    system: yes
    shell: /sbin/nologin
    create_home: false
  tags:
    - tautulli