---
- name: Set up server config
  ansible.builtin.template:
    src: templates/server-config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: "root"
    group: "root"
    mode: 0600
  become: true
  tags:
    - rke2

- name: Enable rke2-server service
  ansible.builtin.service:
    name: rke2-server
    state: "started"
  become: true
  tags:
  - rke2
