---
- name: Check if npm is available
  ansible.builtin.shell:
    cmd: which npm
  register: result_npm_check

- name: Install gamedig
  ansible.builtin.command:
    cmd: npm install gamedig -g
  when: result_npm_check.stdout.find('npm') != -1

