---
- name: retrieve libssl 1.0 (32-bit)
  get_url:
    url: http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.10_i386.deb
    dest: /root/libssl1.0.0_1.0.2n-1ubuntu5.10_i386.deb

- name: install libssl 1.0 (32-bit)
  ansible.builtin.apt:
    deb: /root/libssl1.0.0_1.0.2n-1ubuntu5.10_i386.deb

- name: retrieve libssl 1.0 (64-bit)
  get_url:
    url: http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.10_amd64.deb
    dest: /root/libssl1.0.0_1.0.2n-1ubuntu5.10_amd64.deb

- name: install libssl 1.0 (64-bit)
  ansible.builtin.apt:
    deb: /root/libssl1.0.0_1.0.2n-1ubuntu5.10_amd64.deb
