---
- name: Add 32bit architecture installation for Debian
  ansible.builtin.import_tasks: debian-32bit.yml
  tags:
    - barotrauma

- name: Add packages for Debian
  ansible.builtin.import_tasks: debian-packages.yml
  tags:
    - barotrauma

- name: Install GameDig
  ansible.builtin.import_tasks: debian-gamedig.yml
  tags:
    - barotrauma

- name: Create btserver user
  ansible.builtin.user:
    name: btserver
    shell: /bin/bash
    append: yes
    groups:
      - staff
  tags:
    - barotrauma

- name: Create Ansible temp directory
  ansible.builtin.command:
    cmd: mkdir -p /home/btserver/.ansible/tmp
  changed_when: false
  become: true
  become_user: btserver
  tags:
    - barotrauma

- name: Retrieve LinuxGSM script
  ansible.builtin.get_url:
    url: https://linuxgsm.sh
    dest: /home/btserver/linuxgsm.sh
    mode: 0755
  become: true
  become_user: btserver
  tags:
    - barotrauma

- name: Register if the LGSM script has been installed
  ansible.builtin.stat:
    path: /home/btserver/linuxgsm.sh
  register: linuxgsm_script
  tags:
    - barotrauma

- name: Install Barotrauma module
  ansible.builtin.command:
    cmd: ./linuxgsm.sh btserver
    chdir: /home/btserver
  when: linuxgsm_script.stat.exists
  changed_when: btserver_script.stat.isdir is defined
  become: true
  become_user: btserver
  tags:
    - barotrauma

- name: Register if the Barotrauma script has been installed
  ansible.builtin.stat:
    path: /home/btserver/btserver
  register: btserver_script
  tags:
    - barotrauma

- name: Install Barotrauma
  ansible.builtin.command:
    cmd: ./btserver auto-install
    chdir: /home/btserver
  changed_when: false
  become: true
  become_user: btserver
  tags:
    - barotrauma

- name: Apply hotfixes for Debian
  ansible.builtin.import_tasks: debian-hotfixes.yml
  tags:
    - barotrauma

- name: Ensure local share directory exists
  ansible.builtin.file:
    path: "/home/btserver/.local/share/Daedalic Entertainment GmbH/Barotrauma"
    state: directory
    mode: 0755
    group: btserver
    owner: btserver
  tags:
    - barotrauma

- name: Register if a Multiplayer mount exists
  ansible.builtin.stat:
    path: /data/Multiplayer
  register: multiplayer_mount
  tags:
    - barotrauma

- name: Link Multiplayer mount
  ansible.builtin.file:
    src: /data/Multiplayer
    path: "/home/btserver/.local/share/Daedalic Entertainment GmbH/Barotrauma/Multiplayer"
    state: link
  when: multiplayer_mount.stat.exists
  tags:
    - barotrauma

- name: Install serverscripts
  ansible.builtin.import_tasks: serverscripts.yml
  tags:
    - barotrauma
