---
- name: Add source repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://archive.canonical.com/ubuntu jammy multiverse
    state: present

- name: Accept Steam license (question)
  ansible.builtin.debconf:
    name: steam
    question: steam/question
    value: 'I AGREE'
    vtype: select

- name: Accept Steam license (license)
  ansible.builtin.debconf:
    name: steam
    question: steam/license
    value: ''
    vtype: note

- name: Ensure build dependencies
  ansible.builtin.apt:
    pkg:
      - bc
      - binutils
      - bsdmainutils
      - bzip2
      - ca-certificates
      - curl
      - dos2unix
      - file
      - gzip
      - jq
      - lib32gcc-s1
      - lib32stdc++6
      - libicu-dev
      - libsdl2-2.0-0:i386
      - netcat
      - python3
      - steamcmd
      - tar
      - tmux
      - util-linux
      - unzip
      - wget
  environment:
    DEBIAN_FRONTEND: noninteractive
