---
- name: Check if npm is available
  ansible.builtin.command:
    cmd: which npm
  changed_when: false
  failed_when: false
  register: result_npm_check
  tags:
    - barotrauma

- name: Install gamedig
  ansible.builtin.command:
    cmd: npm install gamedig -g
  when: result_npm_check.stdout.find('npm') != -1
  changed_when: false
  tags:
    - barotrauma
