---
- name: add source repository into sources list
  apt_repository:
    repo: deb http://archive.canonical.com/ubuntu jammy multiverse
    state: present

- name: add 32bit architecture installation for Debian
  import_tasks: debian-32bit.yml

- name: ensure build dependencies
  apt:
    pkg:
      - apt-transport-https
      - lib32gcc-s1
      - steamcmd
      - wget

- name: install .NET depedencies for Debian
  import_tasks: debian-dotnet.yml

- name: create steam user
  user:
    name:  steam
    shell: /bin/bash

- name: ensure config directory exists
  file: path=/home/steam/barotrauma-dedicated/Data state=directory

- name: copy default configuration
  template:
    src:   clientpermissions.xml.j2
    dest:  /home/steam/barotrauma-dedicated/Data/clientpermissions.xml
    owner: steam
    group: steam
    mode:  0644
  notify:
    - reload systemctl
