---
- name: Add 32bit architecture installation for Debian
  import_tasks: debian-32bit.yml

- name: Add packages for Debian
  import_tasks: debian-packages.yml

- name: Install GameDig
  import_tasks: debian-gamedig.yml

- name: Create btserver user
  user:
    name: btserver
    shell: /bin/bash
    append: yes
    groups:
      - staff

- name: Create Ansible temp directory
  shell:
    cmd: mkdir -p /home/btserver/.ansible/tmp
  become: true
  become_user: btserver

- name: Retrieve LinuxGSM script
  get_url:
    url: https://linuxgsm.sh
    dest: /home/btserver/linuxgsm.sh
    mode: '755'
  become: true
  become_user: btserver

- name: Install Barotrauma module
  shell:
    cmd: ./linuxgsm.sh btserver
    chdir: /home/btserver
  become: true
  become_user: btserver

- name: Install Barotrauma
  shell:
    cmd: ./btserver auto-install
    chdir: /home/btserver
  become: true
  become_user: btserver

- name: Apply hotfixes for Debian
  import_tasks: debian-hotfixes.yml

- name: Ensure local share directory exists
  file:
    path: "/home/btserver/.local/share/Daedalic Entertainment GmbH/Barotrauma"
    state: directory
    mode: 0755
    group: btserver
    owner: btserver

- name: Register if a Multiplayer mount exists
  stat:
    path: /data/Multiplayer
  register: multiplayer_mount

- name: Link Multiplayer mount
  file:
    src: /data/Multiplayer
    path: "/home/btserver/.local/share/Daedalic Entertainment GmbH/Barotrauma/Multiplayer"
    state: link
  when: multiplayer_mount.stat.exists

- name: Install serverscripts
  import_tasks: serverscripts.yml
