---
- name: add source repository into sources list
  apt_repository:
    repo: deb http://archive.canonical.com/ubuntu jammy multiverse
    state: present

- name: add 32bit architecture installation for Debian
  import_tasks: debian-32bit.yml

- name: ensure build dependencies
  apt:
    pkg:
      - apt-transport-https
      - lib32gcc-s1
      - steamcmd
      - wget

- name: install .NET depedencies for Debian
  import_tasks: debian-dotnet.yml

- name: create steam user
  user:
    name:  steam
    shell: /bin/bash

- name: install Barotrauma
  shell:
    cmd: |
      steamcmd \
      @ShutdownOnFailedCommand \
      @NoPromptForPassword \
      +login anonymous \
      +force_install_dir /home/steam/barotrauma-dedicated \
      +app_update 1026340 validate \
      +'quit'
  become: true
  become_user: steam

- name: create steamclient.so symlink
  shell:
    cmd: |
      mkdir -p /home/steam/.steam/sdk64 && \
      chown -R steam:steam /home/steam/.steam && \
      ln -s /home/steam/barotrauma-dedicated/steamclient.so /home/steam/.steam/sdk64/steamclient.so

- name: ensure multiplayer save directory exists
  shell:
    cmd: |
      mkdir -p /home/steam/.local/share/Daedalic\ Entertainment\ GmbH/Barotrauma/Multiplayer && \
      chown -R steam:steam /home/steam/.local/share/Daedalic\ Entertainment\ GmbH

- name: ensure config directory exists
  file: path=/home/steam/barotrauma-dedicated/Data state=directory

- name: copy default configuration
  template:
    src:   clientpermissions.xml.j2
    dest:  /home/steam/barotrauma-dedicated/Data/clientpermissions.xml
    owner: steam
    group: steam
    mode:  0644
  notify:
    - reload systemctl
