- name: download .NET runtime dependencies
  get_url:
    url:  https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb
    mode: '0440'

- name: install .NET runtime repos
  apt:
    deb:  /tmp/packages-microsoft-prod.deb
    sudo: true    

- name: install .NET runtime depdencies
  apt:
    pkg:
      - dotnet-runtime-3.1
    update_cache: yes