---
- name: add source repository into sources list
  apt_repository:
    repo: deb http://archive.canonical.com/ubuntu jammy multiverse
    state: present

- name: add 32bit architecture installation for Debian
  import_tasks: debian-32bit.yml

- name: accept Steam license (question)
  debconf:
    name: steam
    question: steam/question
    value: 'I AGREE'
    vtype: select

- name: accept Steam license (license)
  debconf:
    name: steam
    question: steam/license
    value: ''
    vtype: note

- name: ensure build dependencies
  apt:
    pkg:
      - bc
      - binutils
      - bsdmainutils
      - bzip2
      - ca-certificates
      - curl
      - file
      - gzip
      - jq
      - lib32gcc-s1
      - lib32stdc++6
      - libicu-dev
      - libsdl2-2.0-0:i386
      - netcat
      - python3
      - steamcmd
      - tar
      - tmux
      - util-linux
      - unzip
      - wget
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: create btserver user
  user:
    name:  btserver
    shell: /bin/bash

- name: create Ansible temp directory
  shell:
    cmd: mkdir -p /home/btserver/.ansible/tmp
  become: true
  become_user: btserver

- name: retrieve LinuxGSM script
  get_url:
    url: https://linuxgsm.sh
    dest: /home/btserver/linuxgsm.sh
    mode: '755'
  become: true
  become_user: btserver

- name: install Barotrauma module
  shell:
    cmd: ./linuxgsm.sh btserver
    chdir: /home/btserver
  become: true
  become_user: btserver

- name: install Barotrauma
  shell:
    cmd: ./btserver auto-install
    chdir: /home/btserver
  become: true
  become_user: btserver

- name: ensure local share directory exists
  file:
    path: "/home/btserver/.local/share/Daedalic Entertainment GmbH/Barotrauma"
    state: directory
    mode: 0755
    group: btserver
    owner: btserver

- name: register if a Multiplayer mount exists
  stat:
    path: /data/Multiplayer
    register: multiplayer_mount

- name: register if a Data mount exists
  stat:
    path: /data/Data
    register: data_mount

- name: link Multiplayer mount
  file:
    src: /data/Multiplayer
    path: "/home/btserver/.local/share/Daedalic Entertainment GmbH/Barotrauma/Multiplayer"
    state: link
    group: btserver
    owner: btserver
  when: multiplayer_mount.stat.exists

- name: link Data mount
  file:
    src: /data/Data
    path: "/home/btserver/.local/share/Daedalic Entertainment GmbH/Barotrauma/Data"
    state: link
    group: btserver
    owner: btserver
  when: data_mount.stat.exists
