---
- name: Add serversettings.xml
  ansible.builtin.template:
    src: serversettings.xml.j2
    dest: /home/btserver/serverfiles/serversettings.xml
    owner: btserver
    group: btserver
    mode: 0775
  tags:
    - barotrauma

- name: Add clientpermissions.xml
  ansible.builtin.template:
    src: clientpermissions.xml.j2
    dest: /home/btserver/serverfiles/Data/clientpermissions.xml
    owner: btserver
    group: btserver
    mode: 0775
  tags:
    - barotrauma
