---
- name: Copy the public key to the target host
  ansible.builtin.command:
    cmd: >
      "sshpass -e ssh-copy-id
       -i {{ ssh_copy_id_private_key }}
       -o StrictHostKeyChecking=no
       -p {{ ssh_copy_id_ssh_port }}
      {{ ssh_copy_id_username }}@{{ ssh_copy_id_hostname }}"

  changed_when: false
  environment:
    SSHPASS: "{{ ssh_copy_id_password }}"
  tags:
    - ssh_copy_id
