---
- name: Copy the public key to the target host
  ansible.builtin.command:
    cmd: "sshpass -p {{ ssh_copy_id_password }} ssh-copy-id -i {{ ssh_copy_id_private_key }} -o StrictHostKeyChecking=no {{ ssh_copy_id_username }}@{{ ssh_copy_id_hostname }} -p {{ ssh_copy_id_port }}"
  tags:
    - ssh_copy_id