---
- name: Retrieve and extract the Kavita release
  ansible.builtin.unarchive:
    src: https://github.com/Kareadita/Kavita/releases/download/{{ kavita_version }}/kavita-linux-x64.tar.gz
    dest: {{ workingdirectory }}
    extra_opts:
      - "--no-same-owner"
  tags:
    - kavita
