---
- name: Create kavita system group
  ansible.builtin.group:
    name: kavita
    system: yes
  tags:
    - kavita

- name: Create kavita user
  ansible.builtin.user:
    name: kavita
    group: kavita
    system: yes
    shell: /sbin/nologin
    create_home: false
  tags:
    - kavita
