---
- name: Download linodedns_update script
  get_url:
    url: https://raw.githubusercontent.com/frozenfoxx/util/main/network/linodedns_update.sh
    dest: /root/linodedns_update.sh
    mode: 0750

- name: Set the cron to run the update script
  cron:
    name: "Update Linode DNS"
    minute: 0
    job: "API_KEY=\"{{ linodedns_api_key }}\" DOMAIN=\"{{ linodedns_domain }}\" SUBDOMAIN=\"{{ linodedns_subdomain }}\" /root/linodedns_update.sh"
