---
- name: Handle dependencies for Debian
  ansible.builtin.import_tasks: debian-dependencies.yml
  when: ansible_facts['os_family']|lower == 'debian'
  tags:
    - linodedns

- name: Download linodedns_update script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/frozenfoxx/util/main/network/linodedns_update.sh
    dest: /root/linodedns_update.sh
    mode: 0750
  tags:
    - linodedns

- name: Set the cron to run the update script
  ansible.builtin.cron:
    name: "Update Linode DNS - {{ item }}.{{ linodedns_domain }}"
    hour: "*/12"
    minute: 0
    job: "TOKEN=\"{{ linodedns_token }}\" DOMAIN=\"{{ linodedns_domain }}\" SUBDOMAIN=\"{{ item }}\" /root/linodedns_update.sh"
  loop: "{{ linodedns_subdomains }}"
  tags:
    - linodedns
