---
- name: Check current docker-compose version
    ansible.builtin.command: docker-compose --version
    register: docker_compose_vsn
    changed_when: false
    failed_when: false
    check_mode: no
    tags:
    - docker

  - set_fact:
      docker_compose_current_version: "{{ docker_compose_vsn.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
    when:
      - docker_compose_vsn.stdout is defined
    tags:
    - docker

  - name: Install or upgrade docker-compose
    ansible.builtin.get_url: 
      url : "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
      dest: /usr/local/bin/docker-compose
      mode: 'a+x'
      force: yes
    when: >
      docker_compose_current_version is not defined
      or docker_compose_current_version is version(docker_compose_version, '<')
    tags:
      - docker