---
- name: Install packages using apt
  ansible.builtin.apt:
    name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
    state: present
    update_cache: yes
  tags:
    - docker

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present
  tags:
    - docker

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
  tags:
    - docker

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: false
  tags:
    - docker

- name: Run and enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  tags:
    - docker

- name: Install docker-compose
  ansible.builtin.import_tasks: debian-compose.yml
  tags:
    - docker