---
- name: Create NFS client mounts
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    opts: "{{ item.opts }}"
    boot: "{{ item.boot }}"
    state: "{{ item.state }}"
    fstype: "{{ item.fstype }}"
  loop: "{{ nfs_client_mounts }}"
  tags:
    - nfs_client
