---
- name: Install certbot
  ansible.builtin.pip:
    name:
      - certbot
      - certbot-nginx
    executable: /usr/bin/pip3
  tags:
    - nginx
    - certbot

- name: Register certbot
  ansible.builtin.shell: |
    certbot -n register --agree-tos --email {{ letsencrypt_email }}
    touch /etc/letsencrypt/.registered
  args:
    creates: /etc/letsencrypt/.registered
  tags:
    - nginx
    - certbot

- name: Setup cronjob for renewal
  ansible.builtin.cron:
    name: certbot-renewal
    job: "/bin/bash -lc '/usr/local/bin/certbot -q renew'"
    minute: "0"
    hour: "14"
  tags:
    - nginx
    - certbot

- name: Get certificate
  ansible.builtin.command:
    cmd: /usr/local/bin/certbot -n --nginx certonly -d '{{ letsencrypt_domain }}'
  args:
    creates: '/etc/letsencrypt/live/{{ letsencrypt_domain }}'
  ignore_errors: true
  tags:
    - nginx
    - certbot
