---
- name: Update containers on Docker hosts
  hosts:
    - docker
  tasks:
    - name: Update repo
      ansible.builtin.command:
        cmd: "task update"
        chdir: "~/docker-bricksandblocks"
      changed_when: True

    - name: Upgrade the host's containers
      ansible.builtin.command:
        cmd: "task upgrade:host"
        chdir: "~/docker-bricksandblocks"
      changed_when: True

    - name: Deploy the host's containers
      ansible.builtin.command:
        cmd: "task deploy:host"
        chdir: "~/docker-bricksandblocks"
      changed_when: True
