---
- name: Install base packages
  hosts:
    - docker
  become: true
  become_user: root
  tasks:
    - name: Install network share packages
      ansible.builtin.package:
        name:
          - cifs-utils
          - nfs-common
          - yq
        state: present

- name: Install roles
  hosts:
    - docker
  become: true
  become_user: root
  roles:
    - avahi
    - python
    - frozenfoxx.mounts
    - geerlingguy.docker
    - frozenfoxx.ctop
    - frozenfoxx.task

- name: Install Docker plugins
  hosts:
    - docker
  become: true
  become_user: root
  tasks:
    - name: Install loki plugin
      community.docker.docker_plugin:
        plugin_name: grafana/loki-docker-driver:latest
        state: enable
        alias: loki