---
- name: Install base packages
  hosts:
    - docker
  become: true
  roles:
    - avahi
    - python

- name: Install extra packages
  hosts:
    - docker
  become: true
  tasks:
    - name: Install network share packages
      ansible.builtin.package:
        name:
          - cifs-utils
          - nfs-common
        state: present

- name: Install Docker
  hosts:
    - docker
  become: true
  tasks:
    - name: Update package cache.
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker packages
      ansible.builtin.include_role:
        name: geerlingguy.docker
