---
- name: Update containers on Docker hosts
  hosts:
    - docker
  become: true
  become_user: root
  tasks:
    - name: Update repo
      ansible.builtin.command:
        cmd: "task update"
        chdir: "~/docker-bricksandblocks"
      changed_when: True

    - name: Set up environment file
      ansible.builtin.command:
        cmd: "task setup:secrets"
        chdir: "~/docker-bricksandblocks"
      changed_when: True

    - name: Upgrade the host's containers
      ansible.builtin.command:
        cmd: "task upgrade:host"
        chdir: "~/docker-bricksandblocks"
      changed_when: True

    - name: Deploy the host's containers
      ansible.builtin.command:
        cmd: "task deploy:host"
        chdir: "~/docker-bricksandblocks"
      changed_when: True

    - name: Clean up the host's containers
      ansible.builtin.command:
        cmd: "task clean"
        chdir: "~/docker-bricksandblocks"
      changed_when: True
