---
name: Syntax
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v1.0.3
        with:
          target: "./"